### ISSUE TITLE
应该将下载新图片，删除旧图片，放到广告倒计时结束之后

### ISSUE THREAD

**Issue by JackiePS** [xiongoahc/LaunchAD#2]
否则会出现，更换图片地址，出现已经把旧的图片删除的情况，这时候还使用缓存就会找不到文件页面黑屏。
- (void)show
{
    //判断本地缓存广告是否存在，存在即显示
    if ([self imageExist]) {
        //设置按钮倒计时
        [_countBtn setTitle:[NSString stringWithFormat:@"跳过%zd", self.showTime] forState:UIControlStateNormal];
        //当前显示的广告图片
        _adView.image = [UIImage imageWithContentsOfFile:_imgPath];
        //当前显示的广告链接
        _clickAdUrl = [UserDefaults valueForKey:adUrl];
        //开启倒计时
        [self startTimer];
        UIWindow *window = [UIApplication sharedApplication].keyWindow;
        [window addSubview:self];
    }else{
        //不管本地是否存在广告图片都获取最新图片
        [self setNewADImgUrl:_imgUrl];
    }
}
- (void)dismiss
{
    [self.countTimer invalidate];
    self.countTimer = nil;
    
    [UIView animateWithDuration:0.1f animations:^{
        
        self.alpha = 0.f;
        
    } completion:^(BOOL finished) {
        
        [self removeFromSuperview];
        //不管本地是否存在广告图片都获取最新图片
        [self setNewADImgUrl:_imgUrl];
    }];
}
这里面解决了这个问题。

**Comment by xiongoahc** [comment]
好长时间没上github了，抱歉。的确，这是一个存在的逻辑问题，谢谢指出！
