### ISSUE TITLE
自问自答:千万不要把代码放到AppDelegate或者UITabBarController里！！！

### ISSUE THREAD

**Issue by jihongboo** [xiongoahc/LaunchAD#3]
自作聪明把代码放到AppDelegate里（作者明明说随便放到那里的呀），结果app界面先铺出来，然后广告页才出来，中间间隔了0.2秒，特别恶心。后来打断点才发现，AppDelegate或者UITabBarController里的非系统方法都是异步执行，目的应该是为了加速app的启动速度吧。总之不要自作聪明把代码放到AppDelegate或者UITabBarController里，老老实实放到app的第一个controller里！！

**Comment by xiongoahc** [comment]
谢谢指正，我会再好好研究研究的。
